# Generated by Django 4.0.4 on 2022-12-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devolu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='celular',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
