# Generated by Django 4.0.4 on 2022-12-11 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Devolu', '0002_alter_adminuser_celular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devolucion',
            old_name='nombre_vendedor',
            new_name='vendedor',
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'group__name': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DCliente',
        ),
    ]
